### PR TITLE
Resolve values in attribute

### PR DESCRIPTION
**Pull request by vijaynalawade**
**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**
Currently, attribute value set to $env.FOO or $property.BAR is not resolved while deserialization which causes runtime failure due to type incompatibility.
`{
    "name": "Prop1",
    "type": "integer",
    "value": "$env.PROP1"
  }
`
**What is the new behavior?**
Before coercing value, value will be resolved using appropriate resolver.

### CODE REVIEW

**Comment by retgits** [comment]
This is pretty cool! Where can I find docs on how to implement a CustomResolver?

**Comment by fm-tibco** [comment]
Not sure what we are trying to do here?  A custom resolver as in something other than property,flow,etc?  or are you also talking about a custom dereferencer other that "$".

**Comment by vijaynalawade** [comment]
@fm-tibco : Intention is to support custom resolvers like **$configprop[SOMETHING]** for Flogo powered products. Though, current requirement is more driven by app property value resolution, in future this will be useful at other places like mappings.

**Comment by vijaynalawade** [comment]
Created another PR

**Pull request closed without merging**
