### PR TITLE
Start trigger in goroutines

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[*] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #166

**What is the current behavior?**
Today engine starts all trigger at main engine thread, main engine goroutine will be blocked if one of trigger fails to release the main engine goroutine.
**What is the new behavior?**
Start all triggers in the different goroutine.

### CODE REVIEW

**Comment by lixingwang** [comment]
BTW, I tested 3 rest triggers and they are working great independently.

**Comment by fm-tibco** [comment]
Is the concern that a trigger gets stuck on intialization?  You want to have it not on the main thread so you can still kill gracefully via a signal?

**Comment by lixingwang** [comment]
@fm-tibco According to our test which more depend on how user develops trigger. for our case, it gets stuck when starting trigger, one of our trigger loops to receive events from AWS, this case the main thread will be stuck in start.  In order to avoid user face this kind of issue, I prefer to start trigger in another thread which doesn't hurt anything.

**Comment by fm-tibco** [comment]
@lixingwang So the issue is that want to start triggers in parallel, so the other triggers aren't waiting for the AWS one to start.  Does this AWS trigger eventually start?  Or is this just a poorly designed trigger that you are trying to work around?

**Comment by lixingwang** [comment]
After discussing with @fm-tibco and @vijaynalawade.   we shouldn't encourage bad coding.  we should enhance the documentation. such as `the start method shouldn't hold on to the thread and must return.`

**Pull request closed without merging**
